### ISSUE TITLE
Icons einbauen, über die auf die Informationsseiten der Arbeitsbereiche springen

### ISSUE THREAD

**Issue by rockgobo** [rockgobo/LIfBi---Webseiten#1]
Über ein Icon soll angezeigt werden, wenn ein Link in den Daten angegeben wurde. Klickt der Nutzer auf diesen Link, wechselt die Seite auf diese URL.

**Comment by Julia-LIfBi** [comment]
Bitte auch über Icon anzeigen, wenn die Abteilung oder der Arbeitsbereich "aufklappbar" sind

**Comment by kathrinerbacher** [comment]
Achtung, Funktion "Aufklappen" funktioniert gerade wieder nicht - oder arbeitest Du gerade daran?

**Comment by rockgobo** [comment]
Ich habe nun vor aufklappbare Bäume einen Knopf gesetzt um die Unterbäume auf und zuzuklappen. Alternativ könnt ihr euch die Struktur noch anschauen, die wir für das Intranet gebaut haben:
https://intern.lifbi.de/Verwaltung/Organisation.aspx vielleicht ist das eine Alternative für den Baum.

**Comment by kathrinerbacher** [comment]
Cool, vielen Dank. Könnte man aber das Wort "weiter" durch ein Symbol ersetzen, also einen Pfeil o.ä.?
Zudem ist uns aufgefallen, dass der Knopf zum Aufklappen bei den Abteilungen verschwindet, wenn man alles einmal zuklappt und dann wieder aufklappen möchte: 
![grafik](https://cloud.githubusercontent.com/assets/25501838/22775083/59105330-eeaa-11e6-8b5f-6fee2a51bf73.png)

**Comment by rockgobo** [comment]
Den Effekt mit dem auf und zuklappen habe ich irgendwie nicht... das Weiter kommt wieder raus, das hatte ich gestern nur kurz eingebaut. Ich hätte auch gern, dass ein + in den Buttons steht, wenn der Baum zugeklappt ist. Aber das System reagiert an der Stelle noch nicht auf die Veränderung.

**Comment by rockgobo** [comment]
Ich hab es geschaft die Iconsammlung Fontawesome mit einzubauen. Falls euch das Icon nicht gefällt könnt ihr mal hier schauen und mit einfach den Namen sagen ;-) 
http://fontawesome.io/cheatsheet/

**Comment by Julia-LIfBi** [comment]
Sehr schön, danke dir! Kannst du es bitte noch so einstellen, dass zu Beginn, wenn man die Seite aufruft, nur die erste Ebene sichtbar ist so wie in Kathrins Screenshot oben? Wenn da dann noch das Symbol zum Aufklappen noch erscheint, schaut es schon ziemlich gut aus.

**Comment by kathrinerbacher** [comment]
Aktuell liegt die Verlinkung nur auf dem Symbol, nicht auf dem zugehörigen Text, kannst Du das noch anpassen bitte?

**Comment by kathrinerbacher** [comment]
Bitte noch "+"-Knöpfe einbauen, damit man auch wieder aufklappen kann. Danke :)

**Comment by rockgobo** [comment]
Ich habe nun schöne Icons für geöffnete und geschlossene Bäume eingefügt. Diese wechseln auch je nachdem ob der Baum geöffnet oder geschlossen ist.

**Comment by rockgobo** [comment]
Der Link zu der nächsten Seite liegt nun auf Name und Icon. Damit schließe ich dieses Issue, sollte noch was sein einfach einen neuen Issue aufmachen.
