### ISSUE TITLE
Archiv für beendete LIfBi-Projekte

### ISSUE THREAD

**Issue by Julia-LIfBi** [rockgobo/LIfBi---Webseiten#11]
Hi Christian, sorry, habe vergessen, eine kurze Beschreibung zum Thema dazuzugeben. Wir sollen alle Drittmittelprojekte auf der LIfBi-Website sichtbar machen. Hast du eine Idee, wie man eine Art Archiv für abgeschlossene Projekte einrichten könnte? Vielleicht eine Seite, auf der die vergangenen Projekte im Überblick aufgeführt werden, jeweils mit Link zur Projektbeschreibung. Also vergleichbar mit dem News-Archiv. Was meinst du?

**Comment by rockgobo** [comment]
Ich meine man kann mit einfachen Seite mit Text arbeiten. Wir werden dazu keine "Verwaltungssoftware" schreiben.
