### ISSUE TITLE
Lebensläufe der Mitarbeiter aus NEPS-data werden im Explorer nicht angezeigt (in Firefox aber schon)

### ISSUE THREAD

**Issue by kathrinerbacher** [rockgobo/LIfBi---Webseiten#12]

**Comment by rockgobo** [comment]
Das skript das die Biografien rendert wurde angepasst und funktioniert nun auch mit der neuen JQuery Funktion. Sandra Buchholz hat zum Beispiel nun einen Lebenslauf.

**Comment by rockgobo** [comment]
Im IE läuft es nun auch.
