### ISSUE TITLE
Tabelle auf der Leitungsseite

### ISSUE THREAD

**Issue by Julia-LIfBi** [rockgobo/LIfBi---Webseiten#14]
Wir möchten die Überschriften in der Leitungs-Tabelle zu den Seiten der Arbeitseinheiten verlinken. Die Darstellung ist momentan blaue Schrift auf blauem Hintergrund ...

**Comment by rockgobo** [comment]
Erklärung: Link Farbe ist blau. 
Aufgabe an mich:
- [x] Diesen Standard in der Tabelle mit der Klasse .neps-table ändern.

**Comment by rockgobo** [comment]
Musst nur noch die Pseudo-Klassen :visited :active ergänzen. War eigentlich erledigt
