### ISSUE TITLE
Startansicht Strukturbaum

### ISSUE THREAD

**Issue by kathrinerbacher** [rockgobo/LIfBi---Webseiten#6]
Danke fürs schnelle Kümmern, schaut echt gut aus. Ein (hoffentlich) letztes noch: Kannst du es bitte noch so einstellen, dass zu Beginn, wenn man die Seite aufruft, nur die erste Ebene sichtbar ist, also so:  
![grafik](https://cloud.githubusercontent.com/assets/25501838/22824689/3f5c173c-ef89-11e6-94c1-09ccc1d660de.png)

**Comment by kathrinerbacher** [comment]
Und beim Durchklicken ist mir noch aufgefallen, dass in der dt. Version bei den Arbeitsbereichen der Verwaltung "+"-Knöpfe sind, die müssten weg, da es hier nichts zum klappen gibt: 
![grafik](https://cloud.githubusercontent.com/assets/25501838/22825348/e8bbfe34-ef8c-11e6-96df-545e3033c15e.png)
DANKE!

**Comment by rockgobo** [comment]
Dann sind vermutlich die Daten falsch, ich schaue sie mir nachher mal an.

**Comment by rockgobo** [comment]
Das war ein Datenfehler, da die letzten Knoten eine leere Menge an Kindern hatte. Ich habe diese entfernt und nun sind die Knöpfe nicht mehr da. Es kann sein, dass dein Browser den alten Baum noch im Cache hat. Dann erstmal "STRG+F5" drücken dann sollten die Knöpfe weg sein.

**Comment by kathrinerbacher** [comment]
Lieber Christian, vielen Dank für die Umsetzungen. Jetzt fehlt nur noch die Startansicht (siehe oben, erster Eintrag des issues).

**Comment by rockgobo** [comment]
Das ganze war jetzt doch ein wenig komplizierter, da ich die sichtbaren Äste, für die Höhen der Boxen grundlegend anders berechnen musste. Dafür sollte es jetzt sauber implementiert sein und euren Erwartungen entsprechen. Schaut euch den Baum einfach mal in Ruhe an und wenn euch noch was auffählt schreibt neue Issues.
