### ISSUE TITLE
Pfeil bei LIfBi

### ISSUE THREAD

**Issue by Julia-LIfBi** [rockgobo/LIfBi---Webseiten#8]
Hi Christian, wie eben besprochen bitte noch den Pfeil bei LIfBi entfernen, weil hier ja kein Link hinterlegt ist:
![grafik](https://cloud.githubusercontent.com/assets/25606027/22881626/b5a8a77e-f1e7-11e6-8637-8febf1614b18.png)

**Comment by rockgobo** [comment]
Wird jetzt abgefragt, das Icon verschwindet, wenn kein href verfügbar ist.
