### ISSUE TITLE
Verlinkungen zu Mitarbeiter-Profilen funktionieren nicht

### ISSUE THREAD

**Issue by Julia-LIfBi** [rockgobo/LIfBi---Webseiten#9]
NEPS-data-Seite: Link von den Team-Mitglieder auf Profilseiten funktioniert nicht, z.B. bei Claudia Karwath:
![grafik](https://cloud.githubusercontent.com/assets/25606027/22929332/697a2948-f2bb-11e6-84b1-36ab490d038a.png)

**Comment by rockgobo** [comment]
Umgestellt auf Id anstelle Vorname_nachname und schon geht es
